{% set version = "0.1" %}

package:
  name: scikit-procrustes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-procrustes/scikit-procrustes-{{ version }}.tar.gz
  sha256: 4a4c2377693a4bd57084fe644ecf140eda9ce6a472d8f42579254c80eaafc4ce

build:
  number: 1000
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
    - numpy >=1.12
    - scipy
    - matplotlib
  run:
    - python
    - numpy >=1.12
    - scipy
    - matplotlib

test:
  imports:
    - skprocrustes

about:
  home: https://github.com/melissawm/skprocrustes/
  license: BSD 2-Clause
  # license_file: LICENSE.rst
  summary: 'This is a scikit for the Weighted Orthogonal Procrustes Problem.'

extra:
  recipe-maintainers:
    - melissawm
    - ocefpaf
