appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VuaLavSIiBrtKJyv6CfedAJ6UTlj65Z7dHZCF2Ie90HDtRCelS8QPtfncLWjOPwdgNtYwWDss27vzP+2H6dic58EdvNy/H6m1HrIhpug4kNvKtWIncKVq8n486uZKBHSJw1Mizxzdj1O5Hu02uDXsJ6xGePgVkgSWyFKS1yo8siB6KiHItNQlstWhD25hTFhUdDnd6RggCF7d2YrLm44jfYYHBHIlXmj1EneuAmpeKpq9YFPaBPm86/0aBQ5poccG63AnnNnTLx1f+ONwxEaZ3AqS9SnHk91swWKHqavE/Wrg8e1zsd5oY2vXeTTxZSre8sBuD+76trPltBWRWaz4sYuTvZ4ryKljUQBsQK2aB9VKyGMOyMfZKLM+UpfFlmbwjtpZrbsaq2uxDugyyEUZS+gJrDqw2hztTiLubVETU3BBRPzzztuPBbYWoPvkGq0x3ugsYMsuZD/CuZd9HtBJT2ZWbN3vU8u2mkmGM5hl9LXsHAwnJeoRfmv8GEnAWov/x5Klab0AVXw4S7JC54ba5QuQzg/L2fplVkUKYpfP6DrsU2/Yw8HeId1+syQ6ah71DYSpFB8h14TE8wH0v0/BufNjFzsFiU/OenjUdjP4Y1plDdJr0MzaZV7hytR+gm+fEum6ghywyQxUHsmyPw+XRFR2WGPPKiue0Yfxy+fQsM=}
conda_forge_output_validation: true
