travis:
  secure:
    BINSTAR_TOKEN: 3oDEuF6TLf1MLL//wYOs09EnQbzSDl8nDyY81rT8kGbNeIJSZGEcR88voDdR4nCyG8d3Hje6xjAZqOWzuQeBM9BFOhmH9fTPBF3VX7NK43nKW6cfyYkLIHmaOQ/HrUJoGQXymUIIQnVOj99uR1OgBdWHhy7tAL14cuOikpNxCbuedd57N8/vGf/sR7H+xi35yIuSax9VxWYVPgZ/QOTDHAdlxcy5xIOlK5DDs/3OwrZx8iN/2cRaY2ZFkwfmzjTQp+YddWuFBTTgQpEig2xMe+cYfYhUQIBSeinrVKoksaTsX2H46tQEj7AtlDHl8O28t/40XWuiTu8aT2rPYHi/5SDKBH/wNyf8/YNsSaHwALb754MhtZrJCFIYDisKIs6EPWkor9gHcwbTCJedVoFJ9lBw8IF9EmZJZEMsrNNOM3ShJSD4K/RlAAgJqVIKwNFpqYMQ0fdQH0yXybp9KFNghxneoj9ud4/qBWwh8Av+xq6dWY1DPVjyeKEl/guTH58LgGjp8IhAwUpYUmVmR+zomp+C6F/vamr4ViF2jHjPsx54HQQctb/esNfBoahsYghTuU/MYtgnXQ5RtCQ8PxRugpo9qDUtvQsn7f9n5RjRsDSYbi9o1NQlOqsTx5Qn3eoCZ+ayXYCrosoxvE9stkQxxnDKLcFS/godm6v7pxgGeN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
